export const TRAINER_LIST_REQUEST = "TRAINER_LIST_REQUEST";
export const TRAINER_LIST_SUCCESS = "TRAINER_LIST_SUCCESS"; // Corrected spelling
export const TRAINER_LIST_FAIL = "TRAINER_LIST_FAIL";

export const TRAINER_DETAILS_REQUEST = "TRAINER_DETAILS_REQUEST";
export const TRAINER_DETAILS_SUCCESS = "TRAINER_DETAILS_SUCCESS"; // Corrected spelling
export const TRAINER_DETAILS_FAIL = "TRAINER_DETAILS_FAIL";
